#include "main.h"
int _putchar(char);
int _putchar(char);
int _putchar(char);
int _putchar(char);
int _putchar(char);
int _putchar(char);
int _putchar(char);
int _putchar(char);
void print_alphabet(void);
